### ISSUE TITLE
LICENSE VIOLATION

### ISSUE THREAD

**Issue by RohitKushvaha01** [trindadedev13/easy-ui#18]
Your library incorporates source code from Lawnchair, which is licensed under the Apache License, Version 2.0 (2004). Removing the copyright notice and license terms from the original source code is a violation of the license conditions, which require that these notices remain intact.

**Comment by trindadedev13** [comment]
> Sua biblioteca incorpora código-fonte do Lawnchair, que é licenciado sob a Apache License, Versão 2.0 (2004). Remover o aviso de direitos autorais e os termos de licença do código-fonte original é uma violação das condições da licença, que exigem que esses avisos permaneçam intactos.

Well, I think you are in the wrong repository, there is no Lawnchair code here, but rather Robok.

**Comment by trindadedev13** [comment]
and also, I'm going to delete this repository, because this lib isn't even used.
